### PR TITLE
Forward console.log/info/error/warn to terminal

### PR DESCRIPTION
**Pull request by TobiasBales**
We introduce a javascript function (puts) that logs to stdout attached to the process running the app.
This also monkey patches console.log/info/error/warn to log to the webview console but also stdout.

### CODE REVIEW

**Comment by noahgibbs** [comment]
Ooh. Yeah, this will conflict a little with my testing change. Want me to update it?

**Comment by TobiasBales** [comment]
that would be lovely - I can do it too but it probably takes 2x as long @noahgibbs

**Comment by Schwad** [comment]
Thanks for this! So to echo back to make sure I understand, 

1. We'll get more logging in our console when the app is running from the JS side
2. This does so with the new 'puts' method?

But 'puts' isn't something we'd be authoring on the backend ourselves right, it's a utility specific to this?

**Comment by noahgibbs** [comment]
Nick: yes, the JS console output will get forwarded to the text console. And the new puts method in the ShoesDSL will also write to console. Console.log isn't normally directly available in ShoesDSL, though I suppose you could now js_eval("console.log('this kinda sucks');").

**Comment by noahgibbs** [comment]
Okay, I've pushed a merge commit.

**Comment by noahgibbs** [comment]
And it was out of date, but at least auto-mergeable.

**Review by noahgibbs — APPROVED** [review]

**Comment by noahgibbs** [comment]
I've approved it. @TobiasBales, make sure my merge looks okay to you and then you should be able to merge it.

**Pull request merged**
